
package formulariosAdmin;

import controladores.AnomaliaController;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Daniel
 */
public class FrmAnomalias extends javax.swing.JInternalFrame {

    private AnomaliaController anomC = new AnomaliaController();
    
    public FrmAnomalias() {
        initComponents();
        this.llenarTabla();
    }

    public void llenarTabla() {
        this.tableAnomalias.setModel( this.anomC.getAnomalias() );
        TableColumnModel tcm = this.tableAnomalias.getColumnModel();
        tcm.removeColumn( tcm.getColumn(0) );
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnomalias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAnomalia = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Anomalias");

        tableAnomalias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableAnomalias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnomaliasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAnomalias);

        textAnomalia.setEditable(false);
        textAnomalia.setColumns(20);
        textAnomalia.setRows(5);
        jScrollPane2.setViewportView(textAnomalia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableAnomaliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnomaliasMouseClicked
        int index = this.tableAnomalias.getSelectedRow();
        
        String txt = String.valueOf(this.tableAnomalias.getModel().getValueAt(index, 0));
        
        this.textAnomalia.setText(txt);
    }//GEN-LAST:event_tableAnomaliasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableAnomalias;
    private javax.swing.JTextArea textAnomalia;
    // End of variables declaration//GEN-END:variables
}
