
package formulariosAdmin;

import controladores.AnomaliaController;
import controladores.CombosController;
import entidades.Anomalia;
import entidades.Departamento;
import entidades.JuntaReceptora;
import entidades.Municipio;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class FrmRegistrarAnomalia extends javax.swing.JInternalFrame {

    
    private CombosController depController = new CombosController();
    private AnomaliaController anomC = new AnomaliaController();
    
    public FrmRegistrarAnomalia() {
        initComponents();
        this.llenarDepart();
    }
    
    
    public void llenarDepart() {
        for(Departamento dep : this.depController.getDepartamentos()) {
            this.cmbDepartamento.addItem(dep);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbJunta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbCentroVotacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAnomalia = new javax.swing.JTextArea();
        btnRegistrarAnom = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Anomalia");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Departamento");

        cmbDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDepartamentoItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Codigo JRV");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Centro de Votación:");

        cmbCentroVotacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbCentroVotacionPropertyChange(evt);
            }
        });

        textAnomalia.setColumns(20);
        textAnomalia.setRows(5);
        jScrollPane1.setViewportView(textAnomalia);

        btnRegistrarAnom.setText("Registrar Anomalia");
        btnRegistrarAnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAnomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarAnom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cmbDepartamento, 0, 136, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCentroVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbJunta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCentroVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarAnom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDepartamentoItemStateChanged
        Departamento dep =  (Departamento) this.cmbDepartamento.getSelectedItem();
        ArrayList<Municipio> municipios = this.depController.getMunicipios(dep.getId());
        this.cmbCentroVotacion.removeAllItems();

        for(Municipio muni : municipios) {
            this.cmbCentroVotacion.addItem(muni);
        }
    }//GEN-LAST:event_cmbDepartamentoItemStateChanged

    private void cmbCentroVotacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbCentroVotacionPropertyChange
        Municipio muni = (Municipio) this.cmbCentroVotacion.getSelectedItem();
        ArrayList<JuntaReceptora> juntas = this.depController.getJuntas(muni.getId());
        this.cmbJunta.removeAllItems();

        for(JuntaReceptora junta : juntas) {
            this.cmbJunta.addItem(junta);
        }
    }//GEN-LAST:event_cmbCentroVotacionPropertyChange

    private void btnRegistrarAnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAnomActionPerformed
        String txt = this.textAnomalia.getText();
        
        if(txt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No deje el informe vacío", "Error", 2);
        } else {
            Anomalia anom = new Anomalia();
            Municipio muni = (Municipio) this.cmbCentroVotacion.getSelectedItem();
            JuntaReceptora junta = (JuntaReceptora) this.cmbJunta.getSelectedItem();
            int idCentro = muni.getId();
            int idJrv = junta.getId();
            
            anom.setIdCentro(idCentro);
            anom.setIdJrv(idJrv);
            anom.setTexto(txt);
            
            String msj = this.anomC.insertarAnomalia(anom);
            JOptionPane.showMessageDialog(this, msj, "Notificacion", 2);
        }
        
    }//GEN-LAST:event_btnRegistrarAnomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAnom;
    /*
    private javax.swing.JComboBox<String> cmbCentroVotacion;
    */
    private javax.swing.JComboBox<Municipio> cmbCentroVotacion;
    /*
    private javax.swing.JComboBox<String> cmbDepartamento;
    */
    private javax.swing.JComboBox<Departamento> cmbDepartamento;
    /*
    private javax.swing.JComboBox<String> cmbJunta;
    */
    private javax.swing.JComboBox<JuntaReceptora> cmbJunta;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAnomalia;
    // End of variables declaration//GEN-END:variables
}
