/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosAdmin;

import formulariosEmpleado.FrmEmpleadoVerificar;
import java.awt.Toolkit;
import javax.swing.JMenu;


/**
 *
 * @author Daniel
 */
public class MdiMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MdiMenuAdmin
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MdiMenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/jadex.png")));
    }
    
    /*METODOS PARA CONTROL DE PRIVILEGIOS DE USUARIOS*/
    
    public void menuSupervisorCentro() {
        JMenu menuSecretario = this.menuBar.getMenu(1);
        JMenu menuRegistrar = this.menuBar.getMenu(2);
        JMenu menuAdministrar = this.menuBar.getMenu(3);
        JMenu menuVigilanteI = this.menuBar.getMenu(4);
        JMenu menuSuperJrv = this.menuBar.getMenu(5);
        menuSecretario.setEnabled(false);
        menuRegistrar.setEnabled(false);
        menuAdministrar.setEnabled(false);
        menuVigilanteI.setEnabled(false);
        menuSuperJrv.setEnabled(false);
    }
    
    public void menuSecretario() {
        JMenu menuSuperCentro = this.menuBar.getMenu(6);
        JMenu menuRegistrar = this.menuBar.getMenu(2);
        JMenu menuAdministrar = this.menuBar.getMenu(3);
        JMenu menuVigilanteI = this.menuBar.getMenu(4);
        JMenu menuSuperJrv = this.menuBar.getMenu(5);
        menuRegistrar.setEnabled(false);
        menuAdministrar.setEnabled(false);
        menuVigilanteI.setEnabled(false);
        menuSuperJrv.setEnabled(false);
        menuSuperCentro.setEnabled(false);
    }
    
    public void menuVigilantePartido() {
        JMenu menuSuperCentro = this.menuBar.getMenu(6);
        JMenu menuRegistrar = this.menuBar.getMenu(2);
        JMenu menuAdministrar = this.menuBar.getMenu(3);
        JMenu menuSecretario = this.menuBar.getMenu(1);
        JMenu menuSuperJrv = this.menuBar.getMenu(5);
        menuRegistrar.setEnabled(false);
        menuAdministrar.setEnabled(false);
        menuSecretario.setEnabled(false);
        menuSuperJrv.setEnabled(false);
        menuSuperCentro.setEnabled(false);
    }
    
    public void menuSupervidorJrv() {
        JMenu menuSuperCentro = this.menuBar.getMenu(6);
        JMenu menuRegistrar = this.menuBar.getMenu(2);
        JMenu menuAdministrar = this.menuBar.getMenu(3);
        JMenu menuSecretario = this.menuBar.getMenu(1);
        JMenu menuVigilanteP = this.menuBar.getMenu(4);
        menuRegistrar.setEnabled(false);
        menuAdministrar.setEnabled(false);
        menuSecretario.setEnabled(false);
        menuVigilanteP.setEnabled(false);
        menuSuperCentro.setEnabled(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuSalir = new javax.swing.JMenu();
        menuVotos = new javax.swing.JMenu();
        itemVerVotos = new javax.swing.JMenuItem();
        itemRegistrarVotante = new javax.swing.JMenuItem();
        itemGenReportes = new javax.swing.JMenuItem();
        itemListarVotantes = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        itemRegVotante = new javax.swing.JMenuItem();
        itemRegCandidato = new javax.swing.JMenuItem();
        itemRegPartido = new javax.swing.JMenuItem();
        itemRegSupervisor = new javax.swing.JMenuItem();
        itemRegSupervisorJrv = new javax.swing.JMenuItem();
        itemRegVigilante = new javax.swing.JMenuItem();
        itemRegEmpleado = new javax.swing.JMenuItem();
        itemAddUser = new javax.swing.JMenuItem();
        menuActualizar = new javax.swing.JMenu();
        itemActualizarVotante = new javax.swing.JMenuItem();
        itemActualizarCandidato = new javax.swing.JMenuItem();
        itemActualizarEmpleado = new javax.swing.JMenuItem();
        menuVigilante = new javax.swing.JMenu();
        itemVigRegAnomalia = new javax.swing.JMenuItem();
        menuSupervisorJrv = new javax.swing.JMenu();
        itemSupJregAnomalia = new javax.swing.JMenuItem();
        menuSupervisorCentro = new javax.swing.JMenu();
        itemSupCregAnomalia = new javax.swing.JMenuItem();
        menuAnomalias = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiero Ser Millonario");

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));
        desktopPane.setFocusable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpeg"))); // NOI18N

        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(209, 209, 209))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Accede redondeado Derecho-20.png"))); // NOI18N
        menuSalir.setText("SALIR");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuBar.add(menuSalir);

        menuVotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Caja-20.png"))); // NOI18N
        menuVotos.setText("Secretario");

        itemVerVotos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mostrar propiedad-16.png"))); // NOI18N
        itemVerVotos.setText("Ver Partidos");
        itemVerVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerVotosActionPerformed(evt);
            }
        });
        menuVotos.add(itemVerVotos);

        itemRegistrarVotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boleta de calificaciones-16.png"))); // NOI18N
        itemRegistrarVotante.setText("Registrar Votante");
        itemRegistrarVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarVotanteActionPerformed(evt);
            }
        });
        menuVotos.add(itemRegistrarVotante);

        itemGenReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Documento-16.png"))); // NOI18N
        itemGenReportes.setText("Reporte de Votos");
        itemGenReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenReportesActionPerformed(evt);
            }
        });
        menuVotos.add(itemGenReportes);

        itemListarVotantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lista-16.png"))); // NOI18N
        itemListarVotantes.setText("Ver Padron");
        itemListarVotantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarVotantesActionPerformed(evt);
            }
        });
        menuVotos.add(itemListarVotantes);

        menuBar.add(menuVotos);

        menuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Historial de pedidos-20.png"))); // NOI18N
        menuRegistro.setMnemonic('f');
        menuRegistro.setText("Registro");

        itemRegVotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegVotante.setMnemonic('o');
        itemRegVotante.setText("Votante");
        itemRegVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegVotanteActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegVotante);

        itemRegCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegCandidato.setMnemonic('s');
        itemRegCandidato.setText("Candidato");
        itemRegCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegCandidatoActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegCandidato);

        itemRegPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegPartido.setMnemonic('a');
        itemRegPartido.setText("Partido");
        itemRegPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegPartidoActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegPartido);

        itemRegSupervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegSupervisor.setMnemonic('x');
        itemRegSupervisor.setText("Supervisor Centro V");
        itemRegSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegSupervisorActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegSupervisor);

        itemRegSupervisorJrv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegSupervisorJrv.setText("Supervisor JRV");
        itemRegSupervisorJrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegSupervisorJrvActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegSupervisorJrv);

        itemRegVigilante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegVigilante.setText("Vigilante Partido");
        itemRegVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegVigilanteActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegVigilante);

        itemRegEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemRegEmpleado.setText("Empleado");
        itemRegEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegEmpleadoActionPerformed(evt);
            }
        });
        menuRegistro.add(itemRegEmpleado);

        itemAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Añadir usuario grupo mujer hombre_16.png"))); // NOI18N
        itemAddUser.setText("Agregar Usuario");
        itemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddUserActionPerformed(evt);
            }
        });
        menuRegistro.add(itemAddUser);

        menuBar.add(menuRegistro);

        menuActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Administrador de dispositivos-20.png"))); // NOI18N
        menuActualizar.setMnemonic('e');
        menuActualizar.setText("Administrar");

        itemActualizarVotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Herramientas del administrador_16.png"))); // NOI18N
        itemActualizarVotante.setMnemonic('t');
        itemActualizarVotante.setText("Votantes");
        itemActualizarVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarVotanteActionPerformed(evt);
            }
        });
        menuActualizar.add(itemActualizarVotante);

        itemActualizarCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Herramientas del administrador_16.png"))); // NOI18N
        itemActualizarCandidato.setMnemonic('y');
        itemActualizarCandidato.setText("Candidatos");
        itemActualizarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarCandidatoActionPerformed(evt);
            }
        });
        menuActualizar.add(itemActualizarCandidato);

        itemActualizarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Herramientas del administrador_16.png"))); // NOI18N
        itemActualizarEmpleado.setText("Empleados");
        itemActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarEmpleadoActionPerformed(evt);
            }
        });
        menuActualizar.add(itemActualizarEmpleado);

        menuBar.add(menuActualizar);

        menuVigilante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Historial de pedidos-20.png"))); // NOI18N
        menuVigilante.setText("Vigilante Partido");

        itemVigRegAnomalia.setText("Registrar Anomalía");
        itemVigRegAnomalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVigRegAnomaliaActionPerformed(evt);
            }
        });
        menuVigilante.add(itemVigRegAnomalia);

        menuBar.add(menuVigilante);

        menuSupervisorJrv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Historial de pedidos-20.png"))); // NOI18N
        menuSupervisorJrv.setText("Supervisor JRV");

        itemSupJregAnomalia.setText("Registrar Anomalía");
        itemSupJregAnomalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupJregAnomaliaActionPerformed(evt);
            }
        });
        menuSupervisorJrv.add(itemSupJregAnomalia);

        menuBar.add(menuSupervisorJrv);

        menuSupervisorCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Historial de pedidos-20.png"))); // NOI18N
        menuSupervisorCentro.setText("Supervisor Centro Votacion");

        itemSupCregAnomalia.setText("Registrar Anomalía");
        itemSupCregAnomalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupCregAnomaliaActionPerformed(evt);
            }
        });
        menuSupervisorCentro.add(itemSupCregAnomalia);

        menuBar.add(menuSupervisorCentro);

        menuAnomalias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mostrar propiedad-16.png"))); // NOI18N
        menuAnomalias.setText("Ver Anomalias");
        menuAnomalias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAnomaliasMouseClicked(evt);
            }
        });
        menuBar.add(menuAnomalias);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void itemRegSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegSupervisorActionPerformed
        FrmRegSupervisor regSup = new FrmRegSupervisor();
        regSup.setVisible(true);
        desktopPane.add(regSup);
        regSup.toFront();
        
    }//GEN-LAST:event_itemRegSupervisorActionPerformed

    private void itemRegCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegCandidatoActionPerformed
        FrmRegCandidato regcand = new FrmRegCandidato();
        regcand.setVisible(true);
        desktopPane.add(regcand);
        regcand.toFront();
    }//GEN-LAST:event_itemRegCandidatoActionPerformed

    private void itemRegEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegEmpleadoActionPerformed
        FrmRegEmpleado regEmp = new FrmRegEmpleado();
        regEmp.setVisible(true);
        desktopPane.add(regEmp);
        regEmp.toFront();
    }//GEN-LAST:event_itemRegEmpleadoActionPerformed

    private void itemRegVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegVotanteActionPerformed
        FrmRegisVotante regVot = new FrmRegisVotante();
        regVot.setVisible(true);
        desktopPane.add(regVot);
        regVot.toFront();
    }//GEN-LAST:event_itemRegVotanteActionPerformed

    private void itemRegPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegPartidoActionPerformed
        FrmRegPartido regpart = new FrmRegPartido();
        regpart.setVisible(true);
        desktopPane.add(regpart);
        regpart.toFront();
    }//GEN-LAST:event_itemRegPartidoActionPerformed

    private void itemRegVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegVigilanteActionPerformed
        FrmRegVigilante regvilan = new FrmRegVigilante();
        regvilan.setVisible(true);
        desktopPane.add(regvilan);
        regvilan.toFront();
    }//GEN-LAST:event_itemRegVigilanteActionPerformed

    private void itemAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddUserActionPerformed
        FrmAgreUsuario agreusua = new FrmAgreUsuario();
        agreusua.setVisible(true);
        desktopPane.add(agreusua);
        agreusua.toFront();
    }//GEN-LAST:event_itemAddUserActionPerformed

    private void itemActualizarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarCandidatoActionPerformed
       FrmActuCandidato actcandidato=new FrmActuCandidato();
       actcandidato.setVisible(true);
       desktopPane.add(actcandidato);
       actcandidato.toFront();
    }//GEN-LAST:event_itemActualizarCandidatoActionPerformed

    private void itemActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarEmpleadoActionPerformed
       FrmActuEmpleado actempleado=new FrmActuEmpleado();
       actempleado.setVisible(true);
       desktopPane.add(actempleado);
       actempleado.toFront();
    }//GEN-LAST:event_itemActualizarEmpleadoActionPerformed

    private void itemActualizarVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarVotanteActionPerformed
        FrmGesVotante gesvot = new FrmGesVotante();
        gesvot.setVisible(true);
        desktopPane.add(gesvot);
        gesvot.toFront();
    }//GEN-LAST:event_itemActualizarVotanteActionPerformed

    private void itemVerVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerVotosActionPerformed
        FrmActuPartido frmPartidos = new FrmActuPartido();
        frmPartidos.setVisible(true);
        desktopPane.add(frmPartidos);
        frmPartidos.toFront();
    }//GEN-LAST:event_itemVerVotosActionPerformed

    private void itemRegistrarVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarVotanteActionPerformed
        FrmRegisVotante regVot = new FrmRegisVotante();
        regVot.setVisible(true);
        desktopPane.add(regVot);
        regVot.toFront();
    }//GEN-LAST:event_itemRegistrarVotanteActionPerformed

    private void itemListarVotantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarVotantesActionPerformed
        FrmLisVotante frmVotantes = new FrmLisVotante();
        frmVotantes.setVisible(true);
        desktopPane.add(frmVotantes);
        frmVotantes.toFront();
    }//GEN-LAST:event_itemListarVotantesActionPerformed
    
    
    private void itemRegSupervisorJrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegSupervisorJrvActionPerformed
        FrmRegSupervisorJunta frmRegSupJunta = new FrmRegSupervisorJunta();
        frmRegSupJunta.setVisible(true);
        desktopPane.add(frmRegSupJunta);
        frmRegSupJunta.toFront();
    }//GEN-LAST:event_itemRegSupervisorJrvActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        FrmEmpleadoVerificar login = new FrmEmpleadoVerificar();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menuSalirMouseClicked

    private void itemGenReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenReportesActionPerformed
        FrmReporteVotos votos = new FrmReporteVotos();
        votos.setVisible(true);
        desktopPane.add(votos);
        votos.toFront();
    }//GEN-LAST:event_itemGenReportesActionPerformed

    private void itemVigRegAnomaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVigRegAnomaliaActionPerformed
        FrmRegistrarAnomalia frmAnom = new FrmRegistrarAnomalia();
        frmAnom.setVisible(true);
        desktopPane.add(frmAnom);
        frmAnom.toFront();
    }//GEN-LAST:event_itemVigRegAnomaliaActionPerformed

    private void itemSupJregAnomaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupJregAnomaliaActionPerformed
        FrmRegistrarAnomalia frmAnom = new FrmRegistrarAnomalia();
        frmAnom.setVisible(true);
        desktopPane.add(frmAnom);
        frmAnom.toFront();
    }//GEN-LAST:event_itemSupJregAnomaliaActionPerformed

    private void itemSupCregAnomaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSupCregAnomaliaActionPerformed
        FrmRegistrarAnomalia frmAnom = new FrmRegistrarAnomalia();
        frmAnom.setVisible(true);
        desktopPane.add(frmAnom);
        frmAnom.toFront();
    }//GEN-LAST:event_itemSupCregAnomaliaActionPerformed

    private void menuAnomaliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAnomaliasMouseClicked
        FrmAnomalias frmAnom = new FrmAnomalias();
        frmAnom.setVisible(true);
        desktopPane.add(frmAnom);
        frmAnom.toFront();
    }//GEN-LAST:event_menuAnomaliasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemActualizarCandidato;
    private javax.swing.JMenuItem itemActualizarEmpleado;
    private javax.swing.JMenuItem itemActualizarVotante;
    private javax.swing.JMenuItem itemAddUser;
    private javax.swing.JMenuItem itemGenReportes;
    private javax.swing.JMenuItem itemListarVotantes;
    private javax.swing.JMenuItem itemRegCandidato;
    private javax.swing.JMenuItem itemRegEmpleado;
    private javax.swing.JMenuItem itemRegPartido;
    private javax.swing.JMenuItem itemRegSupervisor;
    private javax.swing.JMenuItem itemRegSupervisorJrv;
    private javax.swing.JMenuItem itemRegVigilante;
    private javax.swing.JMenuItem itemRegVotante;
    private javax.swing.JMenuItem itemRegistrarVotante;
    private javax.swing.JMenuItem itemSupCregAnomalia;
    private javax.swing.JMenuItem itemSupJregAnomalia;
    private javax.swing.JMenuItem itemVerVotos;
    private javax.swing.JMenuItem itemVigRegAnomalia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuActualizar;
    private javax.swing.JMenu menuAnomalias;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSupervisorCentro;
    private javax.swing.JMenu menuSupervisorJrv;
    private javax.swing.JMenu menuVigilante;
    private javax.swing.JMenu menuVotos;
    // End of variables declaration//GEN-END:variables

}
